name: hannover-messe-iot-edge
services:
    # HiveMQ - MQTT Broker
    hivemq:
        image: hivemq/hivemq-ce:2025.1
        restart: unless-stopped
        ports:
            - "1883:1883" # MQTT
        volumes:
            - ./hivemq/data:/opt/hivemq/data
            - ./hivemq/conf:/opt/hivemq/conf
            - ./hivemq/log:/opt/hivemq/log
    # FlowFuse Device Agent - Edge Gateway
    edge-gateway:
        image: flowfuse/device-agent:latest
        restart: unless-stopped
        ports:
            - "1880:1880" # Node-RED port
        volumes:
            - ./flowfuse/edge-gateway/data:/opt/flowfuse-device
