name: hannover-messe-iot-edge
services:
    # HiveMQ - MQTT Broker
    hivemq:
        image: hivemq/hivemq-ce:2025.1
        restart: unless-stopped
        ports:
            - "1883:1883" # MQTT
        volumes:
            - ./hivemq/data:/opt/hivemq/data
            - ./hivemq/conf:/opt/hivemq/conf
            - ./hivemq/log:/opt/hivemq/log
    # InfluxDB - Time Series Database
    influxdb: 
        image: influxdb:2
        restart: unless-stopped
        ports:
            - "8086:8086" # InfluxDB API port
        volumes:
            - ./influxdb/data:/var/lib/influxdb2
            - ./influxdb/config:/etc/influxdb2
        environment:
            - DOCKER_INFLUXDB_INIT_MODE=${INFLUXDB_INIT_MODE:-setup}
            - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_INIT_ORG}
            - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_INIT_BUCKET}
            - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_INIT_USERNAME}
            - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_INIT_PASSWORD}
            - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_INIT_ADMIN_TOKEN}
    # Telegraf - Data Collection Agent
    telegraf:
        image: telegraf:1.29
        restart: unless-stopped
        volumes:
            - ./telegraf/config:/etc/telegraf
        environment:
            - INFLUXDB_INIT_ORG=${INFLUXDB_INIT_ORG}
            - INFLUXDB_INIT_BUCKET=${INFLUXDB_INIT_BUCKET}
            - INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_INIT_ADMIN_TOKEN}
        depends_on:
            - influxdb
            - hivemq
    # FlowFuse Device Agent - Edge Gateway
    edge-gateway:
        image: flowfuse/device-agent:latest
        restart: unless-stopped
        ports:
            - "1881:1880" # Node-RED port
        volumes:
            - ./flowfuse/edge-gateway/data:/opt/flowfuse-device
    # # FlowFuse Device Agent - Sensor Module
    # sensor-module:
    #     image: flowfuse/device-agent:latest
    #     restart: unless-stopped
    #     ports:
    #         - "1881:1880" # Node-RED port
    #     volumes:
    #         - ./flowfuse/sensor-module/data:/opt/flowfuse-device
